### ISSUE TITLE
Changes to the assignment 

### ISSUE THREAD

**Issue by LeonMusCoden** [Maxinio-berincini/HSG-HS23-DS-Assignment2#3]
Jungs, ihr habt sicher gesehen, dass es einen Hinweis zu dem Assignment gab. Da steht unter anderem drinnen, dass die 2 Links zu Swaggerhub zwar ignoriert werden soll, aber die Keywords, die in dem `<a>` Tag stehen nicht!

Heißt, wir müssen den Code ein wenig umstrukturieren, um das zu berücksichtigen. Sollte nicht lange dauern.

**Comment by Maxinio-berincini** [comment]
Ich hab den Code angepasst und im index.csv stehen jetzt die zwei Keywords inkl. Hyperlinks. Jedoch geben die Test ein Error.

**Comment by Maxinio-berincini** [comment]
Done: https://github.com/Maxinio-berincini/HSG-HS23-DS-Assignment2/commit/d10fc76205c85dc893b2dd3116d8982c76d2c9a1
